### ISSUE TITLE
Remove src

### ISSUE THREAD

**Issue by gingur** [yahoo/fluxible-immutable-utils#50]
I don't see any current references to the `/src` directory, is this needed? Can it be deleted?

**Comment by akshayp** [comment]
@gingur It's the raw source for `/lib/ImmutableStore.js`. Babel is used to transpile it into the lib directory

**Comment by koulmomo** [comment]
really, you should `.npmingnore` `src` and `.gitignore` `lib`

**Comment by gingur** [comment]
@akshayp I now see your babel process in your grunt script, can you shed some light on why only one of the five files in `lib` is from `src`? I recently put some changes into `createImmutableStore` but it seems I need to also add them to the `src/ImmutableStore` .. or maybe I don't understand the diff between the two?

**Comment by snyamathi** [comment]
@gingur All of the modules are es5 with the exception of ImmutableStore.  It's written using es6 class syntax because it extends the class `BaseStore`.

There isn't full support for classes yet https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes so it has to be transpiled into es5.  All the other libs are fine as-is, only ImmutableStore needs transpilation.

There are a lot of other ways to rearrange this, such as a src and dist folder but that's another issue.  Hopefully this explains why we have the src folder though.
